config/routes.rb
Buscajolo::Application.routes.draw do
  resources :comentarios, only: [:index, :show, :edit, :update, :destroy]

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  
  resources :analises, only: [:index, :show, :edit, :update, :destroy] do
    resources :comentarios
  end
  resources :produtos

  resources :fornecedors, path: "fornecedores" do
    resources :analises#, shallow: true
  end

  get "busca/index"

  get "busca/results", as: "results"

  root :to => 'busca#index'

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  attr_accessible :texto, :titulo, :user_id
  belongs_to :user
  belongs_to :analise
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  # GET /comentarios
  # GET /comentarios.json
  def index
    if params[:analise_id]
      @comentarios = Comentario.find_all_by_analise_id(params[:analise_id])
      @analise = Analise.find_by_id(params[:analise_id])
    else
      @comentarios = Comentario.all
    end 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comentarios }
    end
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comentario }
    end
  end

  # GET /comentarios/new
  # GET /comentarios/new.json
  def new
    @comentario = Comentario.new
    @analise = Analise.find_by_id(params[:analise_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comentario }
    end
  end

  # GET /comentarios/1/edit
  def edit
    @comentario = Comentario.find(params[:id])
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(params[:comentario])
    @comentario.user = current_user

    @analise = Analise.find_by_id(params[:analise_id])
    @comentario.analise = @analise
    
    respond_to do |format|
      if @comentario.save
        format.html { redirect_to analise_comentarios_path(@analise), notice: 'Comentario foi criado com sucesso.' }
        format.json { render json: @comentario, status: :created, location: @comentario }
      else
        format.html { render action: "new" }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comentarios/1
  # PUT /comentarios/1.json
  def update
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      if @comentario.update_attributes(params[:comentario])
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario = Comentario.find(params[:id])
    @comentario.destroy

    respond_to do |format|
      format.html { redirect_to comentarios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_form.html.haml
= form_for([@analise,@comentario]) do |f|
  - if @comentario.errors.any?
    #error_explanation
      %h2
        = pluralize(@comentario.errors.count, "error")
        prohibited this comentario from being saved:
      %ul
        - @comentario.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :titulo
    = f.text_field :titulo, class: "form-control"
  .form-group
    = f.label :texto
    = f.text_area :texto, class: "form-control"
  .actions
    = f.submit params[:action] == "new" ? "Criar Comentario" : "Atualizar Comentario", class: "btn btn-primary" 

app/views/comentarios/edit.html.haml
.container  
  %h1 Editar comentario
  = render 'form'
  = link_to 'Show', @comentario
  |
  \#{link_to 'Voltar', comentarios_path}

app/views/comentarios/index.html.haml
.container
  - if @analise
    .panel.panel-primary
      .panel-heading
        Analise
      .panel-body

        %p
          %b Titulo:
          = @analise.titulo
        %p
          %b Texto:
          .well
            = @analise.texto
        %p
          %b Fornecedor:
          = link_to @analise.fornecedor.nome, fornecedor_analises_path(@analise.fornecedor)
        %p
          %b Usuario:
          = @analise.user.email
  %h1 Lista de comentarios
  %table.table
    %tr
      %th Titulo
      %th Texto
      %th Usuario
      - if current_user.try(:admin)
        %th 
        %th
        %th
        %th
    - @comentarios.each do |comentario|
      %tr
        %td= comentario.titulo
        %td.well
          = comentario.texto
        %td= comentario.user.email
        - if current_user.try(:admin)
          %td= link_to "Analise", analise_path(comentario.analise) 
          %td= link_to 'Mostrar', comentario
          %td= link_to 'Editar', edit_comentario_path(comentario)
          %td= link_to 'Apagar', comentario, method: :delete, data: { confirm: 'Are you sure?' }  
  / = link_to 'Novo Comentario', new_comentario_path
  %br
  - if @analise
    = link_to new_analise_comentario_path(@analise) , class: "btn btn-default" do
      %span.glyphicon.glyphicon-comment
      Comentar

app/views/comentarios/new.html.haml
.container
  %h1 Novo comentario

  = render 'form'
  = link_to 'Voltar', comentarios_path

app/views/comentarios/show.html.haml
.container
  %p#notice= notice
  %p
    %b Titulo:
    = @comentario.titulo
  %p
    %b Texto:
    = @comentario.texto
  %p
    %b Usuario:
    = @comentario.user.email
  = link_to 'Editar', edit_comentario_path(@comentario)
  |
  \#{link_to 'Voltar', comentarios_path}