config/routes.rb
Buscajolo::Application.routes.draw do
  resources :comentarios, only: [:index, :show, :edit, :update, :destroy]

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  
  resources :analises, only: [:index, :show, :edit, :update, :destroy] do
    resources :comentarios
  end
  resources :produtos

  resources :fornecedors, path: "fornecedores" do
    resources :analises#, shallow: true
  end

  get "busca/index"

  get "busca/results", as: "results"

  root :to => 'busca#index'

end

app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
  has_and_belongs_to_many :produtos
  has_many :analises
  attr_accessible :cidade, :nome

  def lista_nomes_produtos
    self.produtos.map{|p| p.nome}
  end

  def self.search(params)
    for_nome = params[:fornecedor_nome]
    produtos = params[:produtos]

    if for_nome
      results = find(:all, :conditions => ['nome LIKE ?', "%#{for_nome}%"])
    else
      results = find(:all)
    end
    
    if produtos
      results.select {|f| (produtos - f.produtos.map{|p| p.id.to_s}).empty?}
    else
      results
    end

  end

end

app/controllers/fornecedors_controller.rb
class FornecedorsController < ApplicationController
  # GET /fornecedors
  # GET /fornecedors.json
  def index
    @fornecedors = Fornecedor.all
    @produtos = Produto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fornecedors }
    end
  end

  # GET /fornecedors/1
  # GET /fornecedors/1.json
  def show
    @fornecedor = Fornecedor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fornecedor }
    end
  end

  # GET /fornecedors/new
  # GET /fornecedors/new.json
  def new
    @fornecedor = Fornecedor.new
    @produtos = Produto.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fornecedor }
    end
  end

  # GET /fornecedors/1/edit
  def edit
    @produtos = Produto.all
    @fornecedor = Fornecedor.find(params[:id])
  end

  # POST /fornecedors
  # POST /fornecedors.json
  def create
    @fornecedor = Fornecedor.new(params[:fornecedor])

    @fornecedor.produtos = Produto.find_all_by_id(params[:produtos])

    respond_to do |format|
      if @fornecedor.save
        format.html { redirect_to @fornecedor, notice: 'Fornecedor foi criado com sucesso.' }
        format.json { render json: @fornecedor, status: :created, location: @fornecedor }
      else
        format.html { render action: "new" }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fornecedors/1
  # PUT /fornecedors/1.json
  def update
    @fornecedor = Fornecedor.find(params[:id])

    @fornecedor.produtos = Produto.find_all_by_id(params[:produtos])

    respond_to do |format|
      if @fornecedor.update_attributes(params[:fornecedor])
        format.html { redirect_to @fornecedor, notice: 'Fornecedor foi editado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedors/1
  # DELETE /fornecedors/1.json
  def destroy
    @fornecedor = Fornecedor.find(params[:id])
    @fornecedor.destroy

    respond_to do |format|
      format.html { redirect_to fornecedors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fornecedors_helper.rb
module FornecedorsHelper

  # retorna uma string representando todos os produtos que o fornecedor tem
  def produtos_string(fornecedor)
  	prod_st = ""
    fornecedor.lista_nomes_produtos.each do |p_st|
      prod_st << p_st + ", "
    end
    prod_st[0..-3]
  end

  # retorna uma string com o html com labels diferenciadas para os produtos do fornecedor que o usuario buscou
  def produtos_html(fornecedor, produtos)
    prod_html = ""
    if produtos 
      fornecedor.produtos.each do |p|
        if produtos.include? p.id.to_s
          prod_html << '<span class="label label-primary">' + p.nome + '</span>'
        else
          prod_html << '<span class="label label-default">' + p.nome + '</span>'
        end
      end
    else
      fornecedor.produtos.each do |p|
        prod_html << '<span class="label label-default">' + p.nome + '</span>'
      end
    end
    prod_html
  end


end

app/views/fornecedors/_form.html.haml
= form_for(@fornecedor) do |f|
  - if @fornecedor.errors.any?
    #error_explanation
      %h2
        = pluralize(@fornecedor.errors.count, "error")
        prohibited this fornecedor from being saved:
      %ul
        - @fornecedor.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :nome
    = f.text_field :nome, class: "form-control"
  .form-group
    = f.label :cidade
    = f.text_field :cidade, class: "form-control"
  .form-group
    = f.label :produtos
    %br/
    - tem_produto = lambda {|p| @fornecedor.produtos.include? p}
    = select_tag 'produtos', options_from_collection_for_select(@produtos, 'id', 'nome', tem_produto),{:multiple => true, :id => "fornecedor_produtos", "data-placeholder" => "Selecione os produtos..."}
 
  .actions
    = f.submit  params[:action] == "new" ? "Criar Fornecedor" : "Atualizar Fornecedor", class: "btn btn-primary" 

app/views/fornecedors/edit.html.haml
.container
  %h1 Editando fornecedor
  = render 'form'
  = link_to 'Mostrar', @fornecedor
  |
  \#{link_to 'Voltar', fornecedors_path}

app/views/fornecedors/index.html.haml
.container  
  %h1 Lista de fornecedores
  %table.table
    %tr
      %th Nome
      %th Cidade
      %th Produtos
      %th
      %th
      %th
      %th
    - @fornecedors.each do |fornecedor|
      %tr
        %td= fornecedor.nome
        %td= fornecedor.cidade
        %td= produtos_string(fornecedor)
        %td= link_to 'Analises', fornecedor_analises_path(fornecedor)
        %td= link_to 'Mostrar', fornecedor
        %td= link_to 'Editar', edit_fornecedor_path(fornecedor)
        %td= link_to 'Apagar', fornecedor, method: :delete, data: { confirm: 'Tem certeza?' }

  %br/
  = link_to 'Novo Fornecedor', new_fornecedor_path

app/views/fornecedors/new.html.haml
.container
  %h1 Novo fornecedor
  = render 'form'
  = link_to 'Voltar', fornecedors_path

app/views/fornecedors/show.html.haml
.container
  %p
    %b Nome:
    = @fornecedor.nome
  %p
    %b Cidade:
    = @fornecedor.cidade
  %p
    %b Produtos:
    = produtos_string(@fornecedor)
  %p
    = link_to 'Analises', fornecedor_analises_path(@fornecedor)

  = link_to 'Editar', edit_fornecedor_path(@fornecedor)
  |
  \#{link_to 'Voltar', fornecedors_path}