config/routes.rb
Buscajolo::Application.routes.draw do
  resources :comentarios, only: [:index, :show, :edit, :update, :destroy]

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  
  resources :analises, only: [:index, :show, :edit, :update, :destroy] do
    resources :comentarios
  end
  resources :produtos

  resources :fornecedors, path: "fornecedores" do
    resources :analises#, shallow: true
  end

  get "busca/index"

  get "busca/results", as: "results"

  root :to => 'busca#index'

end

app/controllers/busca_controller.rb
class BuscaController < ApplicationController
  def index
    @produtos = Produto.all
  end

  def results
  	@fornecedores = Fornecedor.search(params)
  	@produtos_sel = params[:produtos]
  end
end

app/helpers/busca_helper.rb
module BuscaHelper
end

app/views/busca/index.html.haml
.jumbotron
  .container
    %h2 
      Bem vindo ao Buscajolo!
      = image_tag "/assets/two-storied_house.png"
    %p A procura de materiais de constru&#231;&#227;o? Busque abaixo o que procura e encontre todas as lojas fornecedoras, com an&#225;lises de clientes reais! Por favor, deixe-nos a sua an&#225;lise tamb&#233;m e ajude futuros clientes!
.container
  .panel.panel-primary
    .panel-heading
      Buscar fornecedor!
    .panel-body
      = form_tag results_path, :method => 'get' do
        .form-group
          = label_tag :fornecedor_nome, "Nome do Fornecedor"
          = text_field_tag :fornecedor_nome, params[:fornecedor_nome], class: "form-control", :placeholder => "Nome do Fornecedor"
        .form-group
          = label_tag :produtos
          = select_tag 'produtos', options_from_collection_for_select(@produtos, 'id', 'nome'),{:multiple => true, :id => "fornecedor_produtos", "data-placeholder" => "Selecione os produtos..."}
        .actions
          = button_tag type: 'submit', :name => nil, class: "btn btn-primary"  do
            %span.glyphicon.glyphicon-search
            Buscar


- if user_signed_in? && current_user.admin
  .container
    .row
      .col-md-12
        Admin:
        .btn-group
          = link_to "Fornecedores", fornecedors_path, class: "btn btn-default"
          = link_to "Produtos", produtos_path, class: "btn btn-default"
          = link_to "Analises", analises_path, class: "btn btn-default"
          = link_to "Comentarios", comentarios_path, class: "btn btn-default"



/ Begin page content
/ .container
/   .row
/     .col-md-2{style: "background-color:#eee"}
/       %h4
/         Categorias
/     .col-md-6
/       %h4{style: "text-align:center;"}
/         Produtos
/     .col-md-4
/       %h4{style: "text-align:center;"}
/         Propagandas
/       %a{href: ""}
/         = image_tag "/assets/pedrelandia.png"
      

app/views/busca/results.html.haml
.container
  %h1 Fornecedores achados
  - if !@fornecedores.empty?
    %table.table
      %tr
        %th Nome
        %th Cidade
        %th Produtos
        %th
        %th
      - @fornecedores.each do |fornecedor|
        %tr
          %td= fornecedor.nome
          %td= fornecedor.cidade
          %td= raw produtos_html(fornecedor, @produtos_sel)
          %td
            = link_to fornecedor_analises_path(fornecedor), class: "btn btn-default" do
              %span.glyphicon.glyphicon-eye-open
              Ver Analises
          %td
            = link_to  new_fornecedor_analise_path(fornecedor), class: "btn btn-default" do
              %span.glyphicon.glyphicon-pencil
              Escrever Analise

  - else
    Nenhum fornecedor foi achado com esses dados!