config/routes.rb
Buscajolo::Application.routes.draw do
  resources :comentarios, only: [:index, :show, :edit, :update, :destroy]

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  
  resources :analises, only: [:index, :show, :edit, :update, :destroy] do
    resources :comentarios
  end
  resources :produtos

  resources :fornecedors, path: "fornecedores" do
    resources :analises#, shallow: true
  end

  get "busca/index"

  get "busca/results", as: "results"

  root :to => 'busca#index'

end

app/models/produto.rb
class Produto < ActiveRecord::Base
  has_and_belongs_to_many :fornecedors	
  attr_accessible :nome

  def self.todos_nomes_e_ids
    Produto.all.map{|p| [p.nome, p.id]}
  end

  
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produtos }
    end
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
    @produto = Produto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/new
  # GET /produtos/new.json
  def new
    @produto = Produto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/1/edit
  def edit
    @produto = Produto.find(params[:id])
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(params[:produto])

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto foi criado com sucesso.' }
        format.json { render json: @produto, status: :created, location: @produto }
      else
        format.html { render action: "new" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /produtos/1
  # PUT /produtos/1.json
  def update
    @produto = Produto.find(params[:id])

    respond_to do |format|
      if @produto.update_attributes(params[:produto])
        format.html { redirect_to @produto, notice: 'Produto foi editado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.haml
= form_for(@produto) do |f|
  - if @produto.errors.any?
    #error_explanation
      %h2
        = pluralize(@produto.errors.count, "error")
        prohibited this produto from being saved:
      %ul
        - @produto.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :nome
    = f.text_field :nome, class: "form-control"
  .form-group
    = f.submit params[:action] == "new" ? "Criar Produto" : "Atualizar Produto", class: "btn btn-primary" 

app/views/produtos/edit.html.haml
.container
  %h1 Editando produto
  = render 'form'
  = link_to 'Mostrar', @produto
  |
  \#{link_to 'Voltar', produtos_path}

app/views/produtos/index.html.haml
.container
  %h1 Lista de produtos
  %table.table 
    %tr
      %th Nome
      %th
      %th
      %th
    - @produtos.each do |produto|
      %tr
        %td= produto.nome
        %td= link_to 'Mostrar', produto
        %td= link_to 'Editar', edit_produto_path(produto)
        %td= link_to 'Apagar', produto, method: :delete, data: { confirm: 'Tem certeza?' }
  %br/
  = link_to 'Novo Produto', new_produto_path

app/views/produtos/new.html.haml
.container
  %h1 Novo produto
  = render 'form'
  = link_to 'Voltar', produtos_path
 

app/views/produtos/show.html.haml
.container
  %p
    %b Nome:
    = @produto.nome
  = link_to 'Editar', edit_produto_path(@produto)
  |
  \#{link_to 'Voltar', produtos_path}